
# (APPENDIX) Appendix {-}

# Will you write a reference for me? {#referee}

As employability tutor, I get asked to write lots references for students applying for jobs and further study. I'm happy to do this for my personal tutees. If you've not been a tutee of mine or I've not worked closely with you please read the following:

## Should I ask permission from my referee?
You should always ask the person providing your reference.

## What is a reference for?

References have two main purposes:

1. Providing and confirming *facts*
    i. to give a factual account, e.g. of academic record, attendance, etc
    i. to confirm the accuracy of statements made in an application
1. Providing *opinions*
    i. to give the referee’s opinion as to the candidate’s suitability for the post/course in
question, and his/her potential for the future


## Who can provide a reference for me?

The best person to provide a reference for you is somebody who knows you, such as your personal tutor. See the careers service guide [What are references and how should I choose a referee?](http://www.careers.manchester.ac.uk/applicationsinterviews/faqs/references) and [Guidance to Staff Providing References for Students](http://documents.manchester.ac.uk/display.aspx?DocID=1921) from the University of Manchester.

It is good to have references from different sources, so if you are providing several referees try to pick people from inside and outside the University. Within the University, this is most likely to be your tutor:

* Your personal tutor from year one
* Your personal tutor from year two (if different to first year)
* Your IE tutor (mostly likely me)
* Your third year project supervisor
* Anyone else who knows you personally

If you ask somebody who does not know you very well to write a reference for you, all that they are able to do in a reference is confirm rather dull facts such as your grades, your attendance, start date and graduation date. A referee who does not know you well will be unable to provide opinions, which will not make for a very useful reference.

## How can I help my referee?

It can make it much easier for your referee if you provide them with information you would like them to mention in your reference. This might include information about your character, activities you have completed or specific aspects of your academic performance. Providing an up to date CV also helps your referee.

## Can I have a copy of my reference?
It is unusual for a referee to provide a reference directly to its subject (that's you).

Typically, a referee is asked to provide a reference for a student (or former student) directly by the organisation concerned. For example, if you're applying for postgraduate study, the reference request will be sent by the University directly to your referees email address, who will usually respond by clicking on a link to upload the reference document.

You can make a request to see your reference under data protection law.
